# 2 Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. 

# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do 
# not exceed four million, find the sum of the even-valued terms.




an_minus_2 = 0
an_minus_1 = 1
an = 0
n = 0
sum_of_even = 0

while True:
    n += 1
    if an <= 4000000:
        an = an_minus_1 + an_minus_2
        an_minus_2 = an_minus_1
        an_minus_1 = an
        if not (an % 2):
            sum_of_even += an
    else:
        break
a = sum_of_even
print a